# Generated by Django 4.1 on 2023-04-07 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="journal",
            name="date",
        ),
        migrations.AlterField(
            model_name="journal",
            name="content",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="journal",
            name="title",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
