# Generated by Django 4.2 on 2023-10-13 08:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('patientDirectory', '0001_related_name_patientdirectory'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='enrollmentCode',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
