# Generated by Django 4.2 on 2023-10-13 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientDirectory', '0002_enrollment_enrollmentcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='enrollmentCode',
            field=models.CharField(default='b75e2c', max_length=6, unique=True),
        ),
    ]
