# Generated by Django 4.2 on 2023-10-15 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patientDirectory', '0003_alter_enrollment_enrollmentcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientlist',
            name='enrollmentCode',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='patientDirectory.enrollment'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='enrollmentCode',
            field=models.CharField(default='2r704b', max_length=6, unique=True),
        ),
    ]
