# Generated by Django 4.2 on 2023-10-15 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patientDirectory', '0004_patientlist_enrollmentcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='enrollmentCode',
            field=models.CharField(default='6d8585', max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='patientlist',
            name='enrollmentCode',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patientDirectory.enrollment'),
        ),
    ]
