# Generated by Django 4.2.6 on 2023-11-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientDirectory', '0005_alter_enrollment_enrollmentcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='enrollmentCode',
            field=models.CharField(default='d2b233', max_length=6, unique=True),
        ),
    ]
