# Generated by Django 4.2 on 2023-10-16 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientDirectory', '0005_alter_enrollment_enrollmentcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='enrollmentCode',
            field=models.CharField(default='bce642', max_length=6, unique=True),
        ),
    ]
