# Generated by Django 4.2.6 on 2023-10-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientDirectory', '0006_alter_enrollment_enrollmentcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='enrollmentCode',
            field=models.CharField(default='2a7391', max_length=6, unique=True),
        ),
    ]
