# Generated by Django 4.2 on 2023-10-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientDirectory', '0007_alter_enrollment_enrollmentcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='enrollmentCode',
            field=models.CharField(default='986cb4', max_length=6, unique=True),
        ),
    ]
