# Generated by Django 4.2.6 on 2023-10-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientDirectory', '0009_alter_enrollment_enrollmentcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='enrollmentCode',
            field=models.CharField(default='b71414', max_length=6, unique=True),
        ),
    ]
