# Generated by Django 4.1 on 2023-04-01 21:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patienttype",
            name="email",
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="patienttype",
            name="name",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="patienttype",
            name="user_account",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="registration.useraccounts",
            ),
        ),
        migrations.AlterField(
            model_name="patienttype",
            name="guardian_email",
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="patienttype",
            name="guardian_name",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="patienttype",
            name="guardian_phone_number",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="patienttype",
            name="type",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="useraccounts",
            name="address",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="useraccounts",
            name="birthday",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="useraccounts",
            name="email",
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="useraccounts",
            name="first_name",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="useraccounts",
            name="last_name",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="useraccounts",
            name="latitude",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="useraccounts",
            name="longitude",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="useraccounts",
            name="middle_name",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="useraccounts",
            name="password",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="useraccounts",
            name="phone_number",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="useraccounts",
            name="security_answer",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="useraccounts",
            name="security_question",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="useraccounts",
            name="sex",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="useraccounts",
            name="type",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.CreateModel(
            name="SpecialistType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=30, null=True)),
                ("email", models.EmailField(max_length=50, null=True)),
                ("name", models.CharField(max_length=150, null=True)),
                ("specialization", models.CharField(max_length=150, null=True)),
                ("phone_number", models.CharField(max_length=20, null=True)),
                ("license_number", models.CharField(max_length=30, null=True)),
                ("experience", models.IntegerField(null=True)),
                ("open_time", models.TimeField(null=True)),
                ("close_time", models.TimeField(null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "days_of_week",
                    models.CharField(
                        choices=[
                            ("mon", "Monday"),
                            ("tue", "Tuesday"),
                            ("wed", "Wednesday"),
                            ("thu", "Thursday"),
                            ("fri", "Friday"),
                            ("sat", "Saturday"),
                            ("sun", "Sunday"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "user_account",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="registration.useraccounts",
                    ),
                ),
            ],
        ),
    ]
