# Generated by Django 4.2 on 2023-10-05 07:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_remove_journal_id_journal_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='uuid',
            field=models.CharField(null=True, default=uuid.uuid4, editable=False, max_length=60, primary_key=True, serialize=False),
        ),
    ]
