# Generated by Django 4.1 on 2023-04-04 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("registration", "0002_rename_profiles_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="id",
        ),
        migrations.AddField(
            model_name="profile",
            name="email",
            field=models.EmailField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="profileID",
            field=models.CharField(
                default="7493990e5a94",
                editable=False,
                max_length=12,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="type",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.CreateModel(
            name="Specialist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=150, null=True)),
                ("name", models.CharField(max_length=200, null=True)),
                ("experience", models.IntegerField(null=True)),
                ("licenseNumber", models.CharField(max_length=20, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=150, null=True)),
                ("name", models.CharField(max_length=200, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
