# Generated by Django 4.1 on 2023-04-04 15:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        (
            "registration",
            "0003_remove_profile_id_profile_email_profile_profileid_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="email",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="name",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="user",
        ),
        migrations.RemoveField(
            model_name="specialist",
            name="email",
        ),
        migrations.RemoveField(
            model_name="specialist",
            name="name",
        ),
        migrations.RemoveField(
            model_name="specialist",
            name="user",
        ),
        migrations.AddField(
            model_name="patient",
            name="profile",
            field=models.OneToOneField(
                default="some code",
                on_delete=django.db.models.deletion.CASCADE,
                to="registration.profile",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="specialist",
            name="profile",
            field=models.OneToOneField(
                default="some code",
                on_delete=django.db.models.deletion.CASCADE,
                to="registration.profile",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="profileID",
            field=models.CharField(
                default=uuid.uuid4,
                editable=False,
                max_length=12,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
