# Generated by Django 4.1 on 2023-04-05 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0004_remove_patient_email_remove_patient_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="specialist",
            name="licenseExpiry",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="specialist",
            name="prcID",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
