# Generated by Django 4.1 on 2023-04-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0005_specialist_licenseexpiry_specialist_prcid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specialist",
            name="prcID",
            field=models.ImageField(
                default="default.jpg", null=True, upload_to="prc_pics"
            ),
        ),
    ]
