# Generated by Django 4.1 on 2023-04-05 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0006_alter_specialist_prcid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="specialist",
            name="experience",
        ),
    ]
