# Generated by Django 4.1 on 2023-04-07 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0007_remove_specialist_experience"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="patientType",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
