# Generated by Django 4.1 on 2023-04-11 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0008_patient_patienttype"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="guardianEmail",
            field=models.EmailField(max_length=150, null=True),
        ),
    ]
