# Generated by Django 3.2.18 on 2023-04-16 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_patient_guardianemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='specialistType',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patientType',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.CreateModel(
            name='AdminModerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registration.profile')),
            ],
        ),
    ]
