# Generated by Django 4.1 on 2023-04-01 23:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0002_patienttype_email_patienttype_name_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserAccounts",
            new_name="UserAccount",
        ),
    ]
