# Generated by Django 4.2.6 on 2023-10-17 09:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0010_auto_20230416_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, max_length=60, primary_key=True, serialize=False)),
                ('appointmentStart', models.DateField(null=True)),
                ('appointmentEnd', models.DateField(null=True)),
                ('note', models.TextField(max_length=1500, null=True)),
                ('status', models.CharField(max_length=10, null=True)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='createdBy', to='registration.profile')),
                ('receivedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivedBy', to='registration.profile')),
            ],
        ),
        migrations.CreateModel(
            name='RescheduledAppointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10, null=True)),
                ('newAppointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newAppointment', to='appointments.appointments')),
                ('oldAppointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oldAppointment', to='appointments.appointments')),
                ('rescheduledBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.profile')),
            ],
        ),
        migrations.CreateModel(
            name='DeclinedAppointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=1500, null=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.appointments')),
                ('declinedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.profile')),
            ],
        ),
        migrations.CreateModel(
            name='AcceptedAppointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acceptedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.profile')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.appointments')),
            ],
        ),
    ]
