# Generated by Django 4.2.6 on 2023-10-17 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_auto_20230416_2032'),
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='createdBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.specialist'),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='receivedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.patient'),
        ),
    ]
