# Generated by Django 4.2.6 on 2023-10-17 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointments_createdby_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='receivedBy',
            new_name='patient',
        ),
        migrations.RenameField(
            model_name='appointments',
            old_name='createdBy',
            new_name='specialist',
        ),
    ]
