# Generated by Django 4.2.6 on 2023-10-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_rename_receivedby_appointments_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='appointmentEnd',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='appointmentStart',
            field=models.DateTimeField(null=True),
        ),
    ]
