# Generated by Django 4.2.6 on 2023-10-17 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_appointments_appointmentend_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='note',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
    ]
