# Generated by Django 4.2.6 on 2023-11-06 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_auto_20230416_2032'),
        ('appointments', '0005_alter_appointments_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='createdBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.profile'),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='status',
            field=models.CharField(default='P', max_length=10, null=True),
        ),
    ]
