# Generated by Django 4.1 on 2023-04-07 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("registration", "0008_patient_patienttype"),
    ]

    operations = [
        migrations.CreateModel(
            name="KeywordValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keyword_name", models.CharField(max_length=255)),
                ("key_value", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="SteppingStone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stress_level", models.IntegerField()),
                ("mood_id", models.IntegerField()),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="registration.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="KeywordScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("anger", models.IntegerField()),
                ("anticipation", models.IntegerField()),
                ("joy", models.IntegerField()),
                ("trust", models.IntegerField()),
                ("fear", models.IntegerField()),
                ("surprise", models.IntegerField()),
                ("sadness", models.IntegerField()),
                ("disgust", models.IntegerField()),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="registration.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="KeywordEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keyword_id", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="registration.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CopingStrategyScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("personal", models.TextField()),
                ("personal_desc", models.TextField()),
                ("social", models.TextField()),
                ("social_desc", models.TextField()),
                ("sleep", models.TextField()),
                ("sleep_desc", models.TextField()),
                ("actions", models.TextField()),
                ("actions_desc", models.TextField()),
                ("food", models.TextField()),
                ("food_desc", models.TextField()),
                ("score", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="registration.patient",
                    ),
                ),
                (
                    "stepping_stone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="steppingStones.steppingstone",
                    ),
                ),
            ],
        ),
    ]
