# Generated by Django 4.1 on 2023-04-09 06:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("steppingStones", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="copingstrategyscore",
            name="patient",
        ),
        migrations.RemoveField(
            model_name="copingstrategyscore",
            name="stepping_stone",
        ),
        migrations.RemoveField(
            model_name="keywordentry",
            name="patient",
        ),
        migrations.RemoveField(
            model_name="keywordscore",
            name="patient",
        ),
        migrations.DeleteModel(
            name="KeywordValue",
        ),
        migrations.RemoveField(
            model_name="steppingstone",
            name="mood_id",
        ),
        migrations.AddField(
            model_name="steppingstone",
            name="actions",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="steppingstone",
            name="anger",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="steppingstone",
            name="anticipation",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="steppingstone",
            name="created_at",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="steppingstone",
            name="disgust",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="steppingstone",
            name="fear",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="steppingstone",
            name="food",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="steppingstone",
            name="joy",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="steppingstone",
            name="keywords",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="steppingstone",
            name="mood_level",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="steppingstone",
            name="personal",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="steppingstone",
            name="sadness",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="steppingstone",
            name="score",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="steppingstone",
            name="sleep",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="steppingstone",
            name="social",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="steppingstone",
            name="surprise",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="steppingstone",
            name="trust",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="steppingstone",
            name="stress_level",
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name="CopingStrategyScore",
        ),
        migrations.DeleteModel(
            name="KeywordEntry",
        ),
        migrations.DeleteModel(
            name="KeywordScore",
        ),
    ]
