# Generated by Django 4.1 on 2023-04-10 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("steppingStones", "0002_remove_copingstrategyscore_patient_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="steppingstone",
            name="actions",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="steppingstone",
            name="food",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="steppingstone",
            name="personal",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="steppingstone",
            name="sleep",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="steppingstone",
            name="social",
            field=models.IntegerField(null=True),
        ),
    ]
