# Generated by Django 4.1 on 2023-04-10 18:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        (
            "steppingStones",
            "0003_alter_steppingstone_actions_alter_steppingstone_food_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="steppingstone",
            name="uuid",
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=60),
        ),
        migrations.CreateModel(
            name="Keyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wordValue", models.IntegerField(null=True)),
                ("word", models.CharField(max_length=100, null=True)),
                ("wordCategory", models.CharField(max_length=100, null=True)),
                (
                    "created_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "steppingStones",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="steppingStones.steppingstone",
                    ),
                ),
            ],
        ),
    ]
