# Generated by Django 4.1 on 2023-04-10 18:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("steppingStones", "0004_steppingstone_uuid_keyword"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="keyword",
            name="steppingStones",
        ),
        migrations.AddField(
            model_name="keyword",
            name="uuid",
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=60),
        ),
    ]
