# Generated by Django 4.1 on 2023-04-11 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("steppingStones", "0005_remove_keyword_steppingstones_keyword_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="steppingstone",
            name="actionsDesc",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="steppingstone",
            name="foodDesc",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="steppingstone",
            name="personalDesc",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="steppingstone",
            name="sleepDesc",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="steppingstone",
            name="socialDesc",
            field=models.TextField(null=True),
        ),
    ]
