# Generated by Django 4.1 on 2023-04-11 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "steppingStones",
            "0006_steppingstone_actionsdesc_steppingstone_fooddesc_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="steppingstone",
            old_name="mood_level",
            new_name="moodLevel",
        ),
        migrations.RenameField(
            model_name="steppingstone",
            old_name="stress_level",
            new_name="stresslevel",
        ),
    ]
