# Generated by Django 4.1 on 2023-04-12 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("steppingStones", "0007_rename_mood_level_steppingstone_moodlevel_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="steppingstone",
            old_name="stresslevel",
            new_name="stressLevel",
        ),
    ]
