# Generated by Django 4.1 on 2023-04-14 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("steppingStones", "0008_rename_stresslevel_steppingstone_stresslevel"),
    ]

    operations = [
        migrations.AddField(
            model_name="steppingstone",
            name="copingStrategyDesc",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="steppingstone",
            name="copingStrategyName",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="steppingstone",
            name="copingStrategyScore",
            field=models.IntegerField(null=True),
        ),
    ]
