# Generated by Django 4.1 on 2023-04-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("steppingStones", "0009_steppingstone_copingstrategydesc_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="steppingstone",
            name="feelingDesc",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="steppingstone",
            name="feelingValue",
            field=models.IntegerField(null=True),
        ),
    ]
