# Generated by Django 4.1 on 2023-04-14 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("steppingStones", "0010_steppingstone_feelingdesc_steppingstone_feelingvalue"),
    ]

    operations = [
        migrations.AddField(
            model_name="steppingstone",
            name="feelingName",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="steppingstone",
            name="feelingDesc",
            field=models.TextField(null=True),
        ),
    ]
