# Generated by Django 4.2 on 2023-10-05 01:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('steppingStones', '0011_steppingstone_feelingname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='steppingstone',
            name='id',
        ),
        migrations.AlterField(
            model_name='steppingstone',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=60, primary_key=True, serialize=False),
        ),
    ]
