# Generated by Django 4.2 on 2023-10-06 08:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_auto_20230416_2032'),
        ('consultationNotes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultationnotes',
            name='id',
        ),
        migrations.RemoveField(
            model_name='consultationnotes',
            name='user',
        ),
        migrations.AddField(
            model_name='consultationnotes',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patientProfile', to='registration.profile'),
        ),
        migrations.AddField(
            model_name='consultationnotes',
            name='specialist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specialistProfile', to='registration.patient'),
        ),
        migrations.AddField(
            model_name='consultationnotes',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=60, primary_key=True, serialize=False),
        ),
    ]
