# Generated by Django 4.2 on 2023-10-07 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_auto_20230416_2032'),
        ('consultationNotes', '0002_remove_consultationnotes_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationnotes',
            name='specialist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specialistProfile', to='registration.profile'),
        ),
    ]
