# Generated by Django 4.2 on 2023-10-05 07:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_remove_journal_date_alter_journal_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=60),
        ),
    ]
