# Generated by Django 4.2 on 2023-10-05 07:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_populate_uuid_values'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='id',
        ),
        migrations.AlterField(
            model_name='journal',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=60, primary_key=True, serialize=False),
        ),
    ]
